import { IUser } from 'appState/features/users/usersTypes'

export const usersSeedData: IUser[] = [
  {
    id: '1',
    name: 'John Doe',
    email: 'john.doe@example.com',
    created: '2024-04-23T08:00:00Z',
    active: true,
    profileImgSrc: 'https://randomuser.me/api/portraits/men/1.jpg',
  },
  {
    id: '2',
    name: 'Jane Smith',
    email: 'jane.smith@example.com',
    created: '2024-04-22T10:30:00Z',
    active: true,
    profileImgSrc: 'https://randomuser.me/api/portraits/women/2.jpg',
  },
  {
    id: '3',
    name: 'Michael Johnson',
    email: 'michael.johnson@example.com',
    created: '2024-04-21T15:45:00Z',
    active: false,
    profileImgSrc: 'https://randomuser.me/api/portraits/men/3.jpg',
  },
  {
    id: '4',
    name: 'Emily Brown',
    email: 'emily.brown@example.com',
    created: '2024-04-20T12:20:00Z',
    active: true,
    profileImgSrc: 'https://randomuser.me/api/portraits/women/4.jpg',
  },
  {
    id: '5',
    name: 'David Wilson',
    email: 'david.wilson@example.com',
    created: '2024-04-19T09:10:00Z',
    active: false,
    profileImgSrc: 'https://randomuser.me/api/portraits/men/5.jpg',
  },
  {
    id: '6',
    name: 'Michael Jordan',
    email: 'mjordan23@fly.com',
    created: '2024-04-23T00:00:00.000Z',
    active: true,
    profileImgSrc: 'https://example.com/images/jordan.png',
  },
  {
    id: '7',
    name: 'Serena Williams',
    email: 'serena.champ@tennis.org',
    created: '2024-04-22T15:30:00.000Z',
    active: false,
    profileImgSrc: 'https://example.com/images/serena.jpg',
  },
  {
    id: '8',
    name: 'Albert Einstein',
    email: 'genius@relativity.com',
    created: '2024-04-21T10:10:00.000Z',
    active: true,
    profileImgSrc: 'https://example.com/images/einstein.png',
  },
  {
    id: '9',
    name: 'Marie Curie',
    email: 'madame.science@discovery.ac',
    created: '2024-04-18T12:00:00.000Z',
    active: true,
    profileImgSrc: 'https://example.com/images/curie.jpg',
  },
  {
    id: '10',
    name: 'Leonardo da Vinci',
    email: 'renaissance.man@art.it',
    created: '2024-04-17T08:45:00.000Z',
    active: true,
    profileImgSrc: 'https://example.com/images/davinci.png',
  },
  {
    id: '11',
    name: 'Stephen Hawking',
    email: 'black.holes@cosmos.uk',
    created: '2024-04-16T17:20:00.000Z',
    active: true,
    profileImgSrc: 'https://example.com/images/hawking.jpg',
  },
  {
    id: '12',
    name: 'Frida Kahlo',
    email: 'artista.mx@surrealism.com',
    created: '2024-04-15T09:00:00.000Z',
    active: true,
    profileImgSrc: 'https://example.com/images/kahlo.jpg',
  },
  {
    id: '13',
    name: 'Nelson Mandela',
    email: 'freedom.fighter@southafrica.gov',
    created: '2024-04-14T14:15:00.000Z',
    active: true,
    profileImgSrc: 'https://example.com/images/mandela.jpg',
  },
  {
    id: '14',
    name: 'Marie Kondo',
    email: 'tidying.expert@japan.com',
    created: '2024-04-13T06:30:00.000Z',
    active: false,
    profileImgSrc: 'https://example.com/images/kondo.jpg',
  },
  {
    id: '15',
    name: 'Wolfgang Amadeus Mozart',
    email: 'maestro@music.at',
    created: '2024-04-12T18:45:00.000Z',
    active: true,
    profileImgSrc: 'https://example.com/images/mozart.jpg',
  },
  {
    id: '16',
    name: 'William Shakespeare',
    email: 'bard@literature.uk',
    created: '2024-04-11T00:00:00.000Z',
    active: true,
    profileImgSrc: 'https://example.com/images/shakespeare.jpg',
  },
  {
    id: '17',
    name: 'Emmy Noether',
    email: 'mathematician@germany.edu',
    created: '2024-04-10T12:30:00.000Z',
    active: true,
    profileImgSrc: 'https://example.com/images/noether.jpg',
  },
  {
    id: '18',
    name: 'Vincent van Gogh',
    email: 'starry.night@art.nl',
    created: '2024-04-09T08:15:00.000Z',
    active: true,
    profileImgSrc: 'https://example.com/images/vangogh.jpg',
  },
  {
    id: '19',
    name: 'Charles Darwin',
    email: 'evolution@science.uk',
    created: '2024-04-08T19:00:00.000Z',
    active: false,
    profileImgSrc: 'https://example.com/images/darwin.jpg',
  },
  {
    id: '20',
    name: 'Alan Turing',
    email: 'enigma@computing.uk',
    created: '2024-04-07T07:45:00.000Z',
    active: true,
    profileImgSrc: 'https://example.com/images/turing.jpg',
  },
  {
    id: '21',
    name: 'Ludwig van Beethoven',
    email: 'symphony@music.de',
    created: '2024-04-05T10:00:00.000Z',
    active: true,
    profileImgSrc: 'https://example.com/images/beethoven.jpg',
  },
  {
    id: '22',
    name: 'Aristotle',
    email: 'philosopher@greece.edu',
    created: '2024-04-03T18:45:00.000Z',
    active: true,
    profileImgSrc: 'https://example.com/images/aristotle.jpg',
  },
  {
    id: '23',
    name: 'Confucius',
    email: 'wisdom@china.cn',
    created: '2024-04-02T00:00:00.000Z',
    active: true,
    profileImgSrc: 'https://example.com/images/confucius.jpg',
  },
  {
    id: '24',
    name: 'Plato',
    email: 'academy@greece.edu',
    created: '2024-04-01T12:30:00.000Z',
    active: true,
    profileImgSrc: 'https://example.com/images/plato.jpg',
  },
  {
    id: '25',
    name: 'Nikola Tesla',
    email: 'innovator@science.us',
    created: '2024-03-31T08:15:00.000Z',
    active: true,
    profileImgSrc: 'https://example.com/images/tesla.jpg',
  },
  {
    id: '26',
    name: 'Marie Antoinette',
    email: 'queen@france.gov',
    created: '2024-03-29T07:45:00.000Z',
    active: true,
    profileImgSrc: 'https://example.com/images/marieantoinette.jpg',
  },
  {
    id: '27',
    name: 'Galileo Galilei',
    email: 'astronomer@italy.edu',
    created: '2024-03-28T15:30:00.000Z',
    active: true,
    profileImgSrc: 'https://example.com/images/galilei.jpg',
  },
  {
    id: '28',
    name: 'Jane Austen',
    email: 'pride.prejudice@literature.uk',
    created: '2024-03-27T10:00:00.000Z',
    active: true,
    profileImgSrc: 'https://example.com/images/austen.jpg',
  },
  {
    id: '29',
    name: 'Stephen King',
    email: 'horror.master@writing.com',
    created: '2024-03-26T06:15:00.000Z',
    active: false,
    profileImgSrc: 'https://example.com/images/king.jpg',
  },
  {
    id: '30',
    name: 'Agatha Christie',
    email: 'mystery.queen@literature.uk',
    created: '2024-03-25T18:45:00.000Z',
    active: true,
    profileImgSrc: 'https://example.com/images/christie.jpg',
  },
  {
    id: '31',
    name: 'William Wordsworth',
    email: 'romantic.poet@literature.uk',
    created: '2024-03-24T00:00:00.000Z',
    active: true,
    profileImgSrc: 'https://example.com/images/wordsworth.jpg',
  },
  {
    id: '32',
    name: 'Isaac Asimov',
    email: 'scifi.writer@literature.us',
    created: '2024-03-22T08:15:00.000Z',
    active: false,
    profileImgSrc: 'https://example.com/images/asimov.jpg',
  },
  {
    id: '33',
    name: 'Maya Angelou',
    email: 'poet.activist@literature.us',
    created: '2024-03-21T19:00:00.000Z',
    active: true,
    profileImgSrc: 'https://example.com/images/angelou.jpg',
  },
  {
    id: '34',
    name: 'Pablo Picasso',
    email: 'artist@spain.eu',
    created: '2024-03-19T15:30:00.000Z',
    active: true,
    profileImgSrc: 'https://example.com/images/picasso.jpg',
  },
]
